apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvsecurityrules.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvSecurityRule
    listKind: NvSecurityRuleList
    plural: nvsecurityrules
    singular: nvsecurityrule
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              file:
                items:
                  properties:
                    app:
                      items:
                        type: string
                      type: array
                    behavior:
                      type: string
                    filter:
                      type: string
                    recursive:
                      type: boolean
                  type: object
                type: array
              ingress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              process:
                items:
                  properties:
                    action:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                  type: object
                type: array
              target:
                properties:
                  policymode:
                    type: string
                  selector:
                    properties:
                      criteria:
                        items:
                          properties:
                            key:
                              type: string
                            op:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      original_name:
                        type: string
                    type: object
                type: object
            required:
            - target
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvclustersecurityrules.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvClusterSecurityRule
    listKind: NvClusterSecurityRuleList
    plural: nvclustersecurityrules
    singular: nvclustersecurityrule
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              file:
                items:
                  properties:
                    app:
                      items:
                        type: string
                      type: array
                    behavior:
                      type: string
                    filter:
                      type: string
                    recursive:
                      type: boolean
                  type: object
                type: array
              ingress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              process:
                items:
                  properties:
                    action:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                  type: object
                type: array
              target:
                properties:
                  policymode:
                    type: string
                  selector:
                    properties:
                      criteria:
                        items:
                          properties:
                            key:
                              type: string
                            op:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      original_name:
                        type: string
                    type: object
                type: object
            required:
            - target
            type: object
        type: object
    served: true
    storage: true
