apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      #- 172.17.255.1-172.17.255.250    
      - 192.168.1.10-192.168.1.255

